# 예외란?
- 프로그램 실행 중에 발생하는 비정상 상황을 의미한다.
- 예외가 발생하면 프로그램이 비정상 종료될 수 있기 때문에 반드시 처리해야 한다.

```java
  int[] arr = new int[3];
  arr[5] = 10; // 배열 범위를 넘어섰으므로 예외 발생 (ArrayIndexOutOfBoundsException)
```

# 예외 처리 기본구조(try-catch)
```java
  try {
      // 예외가 발생할 수 있는 코드
  } catch (Exception e) {
      // 예외 발생 시 처리할 코드
  }
```

# 예외 처리 흐름
1. try 블록 안에서 예외 발생 시
2. catch 블록으로 제어가 넘어감
3. 정상 흐름으로 복귀(프로그램이 멈추지 않음)

# 여러 개의 catch 사용
- 여러 종류의 예외를 구분해 처리 가능

```java
  try {
      int[] arr = new int[3];
      arr[5] = 10;
  } catch (ArrayIndexOutOfBoundsException e) {
      System.out.println("배열 인덱스 범위 초과!");
  } catch (Exception e) {
      System.out.println("그 외 예외 발생!");
  }
```

# finally 블록
- 예외 발생 여부와 관계없이 무조건 실행되는 블록
- 주로 자원 해체(파일 닫기, DB 연결 종료)에 사용

```java
  try {
      System.out.println("작업 시작");
  } catch (Exception e) {
      System.out.println("예외 발생");
  } finally {
      System.out.println("항상 실행되는 블록");
  }
```

# throw 키워드(예외 발생시키기)
- 특정 조건에서 직접 예외를 던질 때 사용

```java
  throw new Exception("직접 예외 발생!");
```

# throws 키워드 (예외 떠넘기기)
- 메서드 선언부에 예외가 발생할 수 있음을 알림
- 해당 메서드를 호출한 쪽에서 예외를 처리해야함

```java
  void myMethod() throws IOException {
      throw new IOException("파일 에러");
  }
```

# 예외 클래스 계층 구조
- 모든 예외 클래스는 Throwable을 상속 받음
-	Exception: 일반 예외(checked exception)
-	RuntimeException: 실행 시 예외(unchecked exception)
-	Error: JVM 관련 심각한 오류 (개발자가 처리 불가)

```text
Throwable
 ├── Exception
 │    ├── IOException
 │    └── SQLException
 └── RuntimeException
      ├── NullPointerException
      ├── ArithmeticException
      └── ArrayIndexOutOfBoundsException
```

# RuntimeException vs Checked Exception

|구분|RuntimeException(unchecked)|Exception(checked)|
|-----|------|--------|
|컴파일러 확인|X(컴파일러가 강제하지 않음)|O(try-catch 필요)|
|예시|NullPointerException, ArithmeticException|IOException, SQLException|

# 커스텀 예외 만들기

```java
  class MyException extends Exception {
      public MyException(String message) {
          super(message);
      }
  }
```
